spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://bdd.objectif-informatique.fr:5432/abm
    username: abm
    password: ABM2018$03
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true